import Navbar from "@/components/navbar/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";
import { Box, Container } from "@mui/material";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Container sx={{ width: "100%", height: "100%" }}>
      <Navbar />
      <Box sx={{ paddingTop: "5rem", display: "flex", height: "100%" }}>
        <Box>
          <Sidebar />
        </Box>
        <Box width={"0.5rem"} />
        <Box sx={{ width: "100%", height: "100%" }}>
          <Box
            sx={{
              padding: "1rem",
              width: "100%",
              height: "100%",
              bgcolor: "var(--bg-white)",
            }}
          >
            {children}
          </Box>
        </Box>
      </Box>
    </Container>
  );
}
